export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const ADD_POKEMON_FAVORITE = "ADD_POKEMON_FAVORITE";
export const REMOVE_POKEMON_FAVORITE = "REMOVE_POKEMON_FAVORITE";
export const LOADING = "LOADING";
